---
name: Bump golang-version to latest version

scms:
  githubConfig:
    kind: github
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: elastic
      repository: stream
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: main

actions:
  stream:
    kind: github/pullrequest
    scmid: githubConfig
    sourceid: latestGoVersion
    spec:
      automerge: false
      labels:
        - dependencies
        - backport-skip
      title: '[Automation] Bump Golang version to {{ source "latestGoVersion" }}'

sources:

  latestGoVersion:
    name: Get Latest Go Release
    kind: githubrelease
    transformers:
      - trimprefix: go
    spec:
      owner: golang
      repository: go
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      versionfilter:
        kind: regex
        pattern: go1\.(\d+)(\.(\d+))?$

  gomod:
    dependson:
      - latestGoVersion
    name: Get version in go.mod format
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^(\d+.\d+)(.\d+)?'
          captureindex: 1
    spec:
      command: echo {{ source "latestGoVersion" }}

conditions:
  dockerTag:
    name: Is docker image golang:{{ source "latestGoVersion" }} published
    kind: dockerimage
    spec:
      image: golang
      tag: '{{ source "latestGoVersion" }}'
    sourceid: latestGoVersion

  goDefaultVersion-check:
    name: Check if defined golang version differs
    kind: shell
    sourceid: latestGoVersion
    spec:
      command: 'grep -v -q {{ source "latestGoVersion" }} .go-version #'

targets:
  update-go-version:
    name: "Update .go-version"
    sourceid: latestGoVersion
    scmid: githubConfig
    kind: file
    spec:
      content: '{{ source "latestGoVersion" }}'
      file: .go-version
      matchpattern: '\d+.\d+.\d+'
  update-dockerfiles:
    name: "Update from dockerfiles"
    sourceid: latestGoVersion
    scmid: githubConfig
    kind: file
    spec:
      content: 'FROM golang:{{ source "latestGoVersion" }}'
      files:
        - Dockerfile
      matchpattern: 'FROM golang:\d+.\d+.\d+'
  update-gomod:
    name: "Update go.mod"
    sourceid: gomod
    scmid: githubConfig
    kind: file
    spec:
      content: 'go {{ source "gomod" }}'
      file: go.mod
      matchpattern: 'go \d+.\d+'
