# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SETUP_GVM_VERSION: "v0.5.1"
  IMAGE_UBUNTU_X86_64: "family/core-ubuntu-2204"
  DOCKER_REGISTRY: "docker.elastic.co"
  DOCKER_IMG: "${DOCKER_REGISTRY}/observability/stream"
  DOCKER_IMG_PR: "${DOCKER_REGISTRY}/observability-ci/stream"
  GO111MODULE: "on"

steps:
  - label: ":golangci-lint: Lint"
    key: "lint"
    command: ".buildkite/scripts/lint.sh"
    notify:
      - github_commit_status:
          context: "Lint"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"

  - label: ":go: Build-${GOLANG_VERSION}"
    key: "build"
    command: "go build"
    notify:
      - github_commit_status:
          context: "Build / ${GOLANG_VERSION}"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
    depends_on: "lint"

  - label: ":go: Test-${GO_VERSION}"
    key: "test"
    command: "gotestsum --format testname --junitfile junit-report.xml -- '-v ./...'"
    notify:
      - github_commit_status:
          context: "Test / ${GOLANG_VERSION}"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
    depends_on: "build"
    artifact_paths: "build/*.xml"

  - label: "Publish PR Docker image"
    key: "publish-pr-img"
    if: build.env("BUILDKITE_PULL_REQUEST") != "false"
    command: "echo test me"
    notify:
      - github_commit_status:
          context: "Publish PR img"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
    depends_on: "build"

  - label: "Publish Docker image"
    key: "publish-nonpr-img"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false"
    command: "echo test me"
    notify:
      - github_commit_status:
          context: "Publish non-PR img"
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
    depends_on: "build"




