#!/usr/bin/env bash

set -euo pipefail

if [[ "$BUILDKITE_PIPELINE_SLUG" == "stream" && "$BUILDKITE_STEP_KEY" == publish* ]]; then
   echo ":: Fetching Pull Requests ::"
   git config remote.origin.fetch "+refs/pull/*/head:refs/remotes/origin/pr/*"
   git fetch
fi
