#!/usr/bin/env bash

set -euo pipefail

source .buildkite/scripts/common.sh

unset_secrets

if [[ "$BUILDKITE_PIPELINE_SLUG" == "stream" && "$BUILDKITE_STEP_KEY" == publish* ]]; then
    docker logout "${DOCKER_REGISTRY}"
fi
